### ISSUE TITLE
Crash when using matter overdrive reactor

### ISSUE THREAD

**Issue by tyler2k15** [TCPR/Thermos#108]
https://gist.github.com/tyler2k15/5c97a55646a01fb58b05

Note: does not crash in single player
Have yet to test in a forge environment

**Comment by Robotia** [comment]
Looks like they've implemented their own model of a tile entity, this is a strange practice that I have seen with some other mods. The issue will likely occur even in vanilla forge. 😕

**Comment by Robotia** [comment]
This problem is not on our end, it seems to be caused by the mod. I looked at their code just now, and this problem is because one of their tile entities /other game objects does not implement the `isInvalid()` method. This could be solved by having the interface `IMultiblockTileEntity` include it, and thus identifying the tile that does not implement isInvalid(). 

You would be better off contacting the mod's developer, @simeonradivoev about this.

**Comment by tyler2k15** [comment]
Note: fixed by https://github.com/simeonradivoev/MatterOverdrive/commit/bb0ee3d926d9fa1713820128fecf9c2bac7ef9f8
