### ISSUE TITLE
Infinity Evolved ModPack FTB Bugs or other issues

### ISSUE THREAD

**Issue by xanthion** [TCPR/Thermos#221]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*

**Explanation of issue:**
For starters, We were running a straight server with FTB Infinity evolved.  We then updated to the latest version of thermos (34), as well as everything running 1.7.10 MC and many things started to break:
 Botania's innate speedbuffs from belts (after about an hour or so it will kick back on until you log out and reboot client then thier not on anymore)
 Scanning with thaumcraft does not unlock new aspects and we are unable to combine aspects in the Research table.
 Unable to load into the top of an inscriber block with an export bus
 creating anything more then 4ks worth of autocrafting in an auto crafter with AE2 immediately closes your client.  This has not happened to me as I haven't done anything as extensive; only someone on the server

**Modpack Name:** *(Only if public)* Infinity Evolved 2.3.5

**Mods Installed:** Infinity Evolved ModPack from FTB v 2.3.5
**Thaumcraft **4,2,3,5; **Botania** r1.8-247; **Applied Energistics 2** rv-stable--10
**Plugins Installed:**

**Warmroast Report:** *(Optional)*

**Thermos Version:** 34

**Forge Version:** 1558

**Comment by Robotia** [comment]
Latest version is 45. Please use that.

**Comment by xanthion** [comment]
Just updated to Thermos-1.7.10-1558.45-server.jar; no changes to the aforementioned issues

**Comment by ajthemacboy** [comment]
Running this modpack too and would also appreciate a fix. Cauldron/KCauldron/Thermos have always acted differently than vanilla Forge; there are a lot of inconsistencies. I know that all three try to optimize Forge, but in my opinion they shouldn't be so destructive about their optimizations, and they should try to maintain as much consistency as possible.

I know this is probably no fault of the Thermos or KCauldron devs, since from what I know much of Thermos is based off Cauldron, but I hope Thermos tries to fix some of these inconsistencies.

**Comment by tyler2k15** [comment]
We are running 1614.45 on our Infinity Evolved 2.3.5 server and are not experiencing the issues mentioned above.

**Comment by Robotia** [comment]
Thermos was forked from build 152 of KCauldron, there are probably inconsistencies due to that. @ajthemacboy most of the breaks are because Forge is not the same as Bukkit. 

Yes there were some performance improvements but that has caused problems only with mods that perform operations that in Java would normally be illegal (i.e. Mobius Core and Opis), i.e. accessing private fields.

If I were 5 people so much more could be done, but I am not, I am a one man team and cannot do this alone. :confused:

**Comment by Robotia** [comment]
@tyler2k15 hmm....then the backport to 1558 is broken
@xanthion @ajthemacboy try 1614.
