### ISSUE TITLE
[Bug] BC pipe and load chunk

### ISSUE THREAD

**Issue by JewishDog** [TCPR/Thermos#225]
**Server Log:** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/C7kN8FKK
**FML Log(s):** *(Use [Pastebin](http://pastebin.com/) or [Github Gist](https://gist.github.com/))*
http://pastebin.com/BpCktA1h
**Explanation of issue:**
https://www.youtube.com/watch?v=g4paBgiRwQQ&feature=youtu.be
**How to recreate this issue:**

**Modpack Name:** *(Only if public)*
Light Delta
**Mods Installed:**
http://prntscr.com/ada2dw
**Plugins Installed:**
Pex,AutoMessage,WE,WG,ChatEx,Essentials
**Warmroast Report:** *(Optional)*

**Thermos Version:**
45-46
**Forge Version:**
1614

**Comment by Razorskills** [comment]
Should probably mention if you tested it on latest build https://github.com/TCPR/Thermos/releases currently build 46. If you haven't tested on build 46, do so and report back.. (It could have already been fixed and your report would be then useless)

**Comment by JewishDog** [comment]
i'm sorry. I tested on build 45-46.

**Comment by Razorskills** [comment]
Can you also see if it happens with the same setup in a single player world? After watching your video I laughed because that used to happen to me back in 1.6.4. Basically the Trash only has one slot to put items in, if the pipe tries to put dirt in the slot but it just put cobblestone in the slot a few milliseconds before that. The trash doesn't clear right away so it has nowhere to put the dirt. Then the item will pop out of the pipe. You could fix that by making a loop so that if it can't go into the trash can, it will loop around and try again for an empty slot.

But test it in SP and report back. I'm pretty sure that is a buildcraft issue. Actually I think it is an intended feature for the pipes if it cannot go anywhere. Thermal Dynamics ducts were created because Buildcraft pipes had issues like these.

**Comment by Robotia** [comment]
@Razorskills vous-etes quebecois?

**Comment by Razorskills** [comment]
Je vis en Saskatchewan. Je me suis arrêté immersion française depuis la 10e année . Je comprends et je lis bien, mais ne l'ai pas pratiqué l'écriture et de parler depuis longtemps.
(This sentence took me soooo long to get half right.. I think there is still some errors ha!)

**Comment by Robotia** [comment]
@Razorskills WESH 
je suis dans une situation similaire, je suis americaine et ma grammaire est abominable...je suis parasseux avec des accents xD

**Comment by DraksterAU** [comment]
Lol Pipes do that if theres nowhere for an item to go. Not a bug....

**Comment by JewishDog** [comment]
@DraksterAU 
If there chunkloader, then pipe the objects go in the trash without a problem, but as soon as I removed chunkloader then began randomly drop

**Comment by DraksterAU** [comment]
Try turning these to true in tileentities.yml 

```
  skip-tileentity-ticks: true
  prevent-invalid-tileentity-updates: true
```

**Comment by JewishDog** [comment]
@DraksterAU 
![image](https://cloud.githubusercontent.com/assets/17753130/13664663/a85bc946-e6b9-11e5-8b24-2b05d63eeaa3.png)

**Comment by Razorskills** [comment]
Doesn't buildcraft have a void pipe?

**Comment by DraksterAU** [comment]
Yup..
