### ISSUE TITLE
Thermos Build 49 Still struggling to render areas with structures (Ruins, ChocolateQuest).

### ISSUE THREAD

**Issue by djoveryde** [TCPR/Thermos#248]
I'm still having issues where if you go into an unrendered area the server tends to lag out while rendering the area along with structures from Ruins Mod.
The server is not crashing this time around, but it does cause players to time out while it renders.

**Comment by Robotia** [comment]
Since this is a lag-related issue, I cannot do anything about this without a profile log or a stall log.

The issue tracker is *not* for making general complaints like this, if you want to do that, do it on Discord. 

I understand you are having issues, but you must also understand that there is absolutely nothing I can do about this with this little information. There is a reason that the template exists, don't just get rid of it and put what you want; you **must** put the relevant WarmRoast/stall logs and you have not done that.

**Comment by djoveryde** [comment]
I generally just get a server is taking longer than expected error. But will grab console output. 
Does wormroast tell you what exactly is taking such a long time and can it be sat actively on a server that has players or is it recommended only for using to produce the error and then remove it?
