### ISSUE TITLE
Bogey-Book User! Stop Using AllUWant

### ISSUE THREAD

**Issue by rustyshakelford2** [TCPR/Thermos#619]
This message comes up whenever someone tries to write a book. A search leads me to believe this is part of Thermos. Is there a way to turn this off?

**Comment by rustyshakelford2** [comment]
Well i'll take that as a no. Explanation please?

**Comment by Sunconure11** [comment]
Thermos is no longer supported, which is probably why this was closed. But I would like to see why I get this all the time too.

I suppose you could use bibliocraft books to get around this, though.

**Comment by sameer** [comment]
I had implemented a fix for an issue that was reported by several Chinese server owners. A mod called "AllUWant" had been used to exploit a bug in Thermos where book metadata is copied from client side to the server without proper verification.

From what I remember, I had made a release without fully testing that the fix had worked, thus breaking book writing/signing. :cry:

**Comment by Sunconure11** [comment]
... Do you have a more recent and up to date with the fix? Or has there been no plans to go back to that after Thermos'  discontinuation, even on your own terms?

**Comment by sameer** [comment]
Since we were having compilation issues and I have been busy with school as of late, it's been difficult to take time to work on Thermos. I had started work on a fix but never got around to testing it.

Also, many modpacks & communities have moved on to newer versions of Minecraft, and the amount of time needed to update Thermos makes it unfeasible to update to 1.8+.

At the moment, I do not have any plans to continue work on Thermos. That said, if someone is interested in continuing work on Thermos, I would gladly give them access to the repository, given that they have the experience and can make the time commitment necessary for such a project.

**Comment by Sunconure11** [comment]
I see.

Thermos on later versions of MC would basically be outshined by Sponge. If you give it to someone, just make sure they do some bugfixes on 1.7.10 or something, unless they are able to handle the competition from Sponge.

**Comment by Time6628** [comment]
Thermos is never going to be on future versions.

**Comment by vediis** [comment]
Would be amazing for this bug to be fixed - many server still run 1.7.10 due to mods not updating. I would gladly throw money at anyone able to fix this issue, I would hate to switch back to Cauldron.

**Comment by Time6628** [comment]
no
