### ISSUE TITLE
[Todo] Chunk.getTile() optimization

### ISSUE THREAD

**Issue by Robotia** [TCPR/Thermos#71]
While making the tutorial video for WarmRoast, I found that Chunk.getTile() lags excessively for high-volume calls. 
This is absolutely ridiculous, considering that there is a maximum of 65536 blocks in a chunk. it could be easily stored as a HashMap<Integer,TileEntity[]> where Integer is hash(x,z) and TileEntity[] is an array of size 256 (for y coordinates).

Will be optimizing these calls in the near future.

**Comment by Cracks777** [comment]
where is the video for warmroast?

**Comment by Robotia** [comment]
https://youtu.be/c0ffjooX7Jw

**Comment by Cracks777** [comment]
Oh it for Linux. is Linux better for a minecraft server or does it really matter?

**Comment by Yive** [comment]
It's personal preference. Personally I think it's better since windows takes up a lot more resources just on it's own which the minecraft server could be using.

Stats:
Windows Server 2002 R2: ~1.5GB usage.
Ubuntu 12.04 LTS / Centos 6.4: 25MB usage.

I haven't owned a machine using windows server for a long time so it's a rough estimate, all I remember is that it would constantly crash due to being a 2GB vps. The linux environments are two of my old unused proxies, but that's what they use with nothing except for nginx running on them.

**Comment by Robotia** [comment]
I highly recommend you use Linux. Running a Windows server is an absolute nightmare.
If you would like, I can try to create some tuts through the Thermos YouTube for how to set one up

**Comment by enterprise12nx** [comment]
@Robotia question, how do i use the latest builds?

**Comment by Robotia** [comment]
@enterprise12nx See https://github.com/TCPR/Thermos/releases . Just added B14, be aware that it requires testing.

**Comment by Bogdan-G** [comment]
MC and MC+any -> have the same consumption on any OS

**Comment by Robotia** [comment]
Not true. Much better memory management on Linux plus tmpfs/ramfs.

**Comment by Robotia** [comment]
@Bogdan-G http://reichel.net/opensource/linuxtop10.html

**Comment by Bogdan-G** [comment]
@Robotia upon a gnome/Arch/Gentoo Linux + OpenJDK/HotSpot 7/8 = Windows 7 memory use, client-side!

**Comment by Robotia** [comment]
@Bogdan-G server does not need GUI, Windows server does.

**Comment by Bogdan-G** [comment]
@Robotia KC no gui.

**Comment by Robotia** [comment]
Command line is amazing, once you learn you will never go back

**Comment by Robotia** [comment]
Done with this change, closing.

**Comment by Bogdan-G** [comment]
@Robotia I know what the command line, no I'm against. Your words are not an argument.
